spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    password: zmqdpqsxvzhodebb
    username: 1902307316@qq.com

  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    block-when-exhausted: true
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000 # 连接超时时间（毫秒）

jwt:
  tokenHeader: Authorization
  secret: ashenone
  expiration: 604800
  tokenHead: Bearer
